import { Inter, Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'],weight: ['400','500','700'] })
import AppProvider from "../utils/AppProvider.js"
import Footer from "../components/footer"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import Header from '../components/home/header.js'
export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={roboto.className}>
      <main className='mx-auto w-4/5'>
      <AppProvider>
      <Header />
      {children}
      <Footer />
      </AppProvider>
      </main>
      </body>
    </html>
   
  )
}
